version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  loadbalancer:
    image: loadbalancer-redisdemo:1.0.0
    container_name: loadbalancer4redisdemo
    ports:
      - 8000:8000
